

export enum DroneEvents {
    ORIENTATION,
    SPEED,
    BATTERY,
    GUIDEDPOINT,
    NAVIGATION,
    ATTITUDE,
    RADIO,
    RC_IN,
    RC_OUT,
    ARMING,
    AUTOPILOT_WARNING,
    MODE,
    STATE,
    MISSION_UPDATE,
    MISSION_RECEIVED,
    TYPE,
    HOME,
    GPS,
    GPS_FIX,
    GPS_COUNT,
    PARAMETER,
    CALIBRATION_IMU,
    CALIBRATION_TIMEOUT,
    HEARTBEAT_TIMEOUT,
    HEARTBEAT_FIRST,
    HEARTBEAT_RESTORED,
    DISCONNECTED,
    CONNECTED,
    MISSION_SENT,
    ARMING_STARTED,
    INVALID_POLYGON,
    MISSION_WP_UPDATE,
    FOLLOW_START,
    FOLLOW_STOP,
    FOLLOW_UPDATE,
    FOLLOW_CHANGE_TYPE,
    WARNING_400FT_EXCEEDED,
    WARNING_SIGNAL_WEAK,
    FIRMWARE,
    WARNING_NO_GPS,
    MAGNETOMETER,
    FOOTPRINT,
    PERIMETER_RECEIVED,
    LEFT_PERIMETER,
    ENFORCING_PERIMETER,
    TEXT_MESSEGE,
    BEACON_BEEP,
    BEACON_LOCK_START,
    BEACON_LOCK_FINISH,
    GCS_LOCATION,
    PROTOCOL_LEARNING,
    PROTOCOL_IDENTIFIED,


    PARAMS_START=1000,
    PARAM_RECEIVE=1001,
    PARAMS_END=1002,
}

export class DroneEvent {

    constructor(public id: DroneEvents, public data: any) {

    }
}